### ISSUE TITLE
Upgrade configuration for Xdebug 3

### ISSUE THREAD

**Issue by lephleg** [Automattic/wordpress-xdebug#7]
Hello! The current configuration of xdebug seems deprecated as the `pecl install "xdebug"` command currently installs Xdebug 3 (`v3.0.3`).

As a result, the config values passed during image build are no longer valid and have to be upgraded using the [official guide](https://xdebug.org/docs/upgrade_guide).

**Comment by dadinugroho** [comment]
I tried this setup and it is working.

My setup
1. Windows 10
2. vscode v1.56.0
3. WSL2 Ubuntu 18.04
4. Docker Engine v20.10.5 on WIndows 10 WSL2 enabled.

`Dockerfile`
```
FROM wordpress:latest
LABEL maintainer Automattic <oscar.lopez@automattic.com>

ENV XDEBUG_PORT 9003

RUN pecl install "xdebug" \
    && docker-php-ext-enable xdebug

RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.discover_client_host=true" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.client_port=${XDEBUG_PORT}" >> /usr/local/etc/php/conf.d/xdebug.ini
```

`docker-compose.yml`
```
version: '3.9'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wp:
    depends_on:
    - db
    image: automattic/wordpress-xdebug
    volumes:
    - ./wp:/var/www/html
    ports:
    - 8080:80
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
```

`launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9003,
            "hostname": "localhost",
            "log": true,
            "pathMappings": {
                "/var/www/html": "${workspaceFolder}/wp"
            },
        }
    ]
}
```

I am a newbie in Docker. May someone elaborate on the significance of having XDEBUG setup in the `docker-compose.yml` and `Dockerfile` ?

`Dockerfile`
```
...
RUN echo "xdebug.mode=develop,debug" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.discover_client_host=true" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.client_port=${XDEBUG_PORT}" >> /usr/local/etc/php/conf.d/xdebug.ini
...
```

`docker-compose.yml`
```
...
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: discover_client_host=true start_with_request=yes client_host=host.docker.internal client_port=9000
...
```

I tried to remove the settings in `docker-compose.yml` and it is still working, but it is not working when I remove the settings in `Dockerfile`.
